[package]
name = "udpserver"
version = "0.1.0"
authors = ["Ramesh Balaji <post2rb@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hangmanstructs = { path = "../hangmanstructs" }
bincode = "1.3.1"
